### ISSUE TITLE
Bootstrap template

### ISSUE THREAD

**Issue by pabloriutort** [pabloriutort/Govern#1]
Para simplificarnos un poco el trabajo del diseño y no empezar nada de cero he pensado en utilizar plantillas de dashboards, que al fin y al cabo es lo que tenemos que desarrollar.
En [esta web](https://colorlib.com/wp/free-bootstrap-admin-dashboard-templates/) he encontrado algunas muy interesantes que son gratuitas, ¿Qué os parecen?

Si encontráis algún recurso mejor o tenéis otra idea podéis comentarla aquí :smile:

**Comment by pabloriutort** [comment]
De la página web que os comentaba me he decantado por este tema, si os parece bien: https://github.com/puikinsh/gentelella

Creo que cubre más o menos nuestras necesidades. Estaría bien que os lo bajarais de la web que os he pasado y me dierais vuestra opinión. 
En concreto en esta plantilla hay 3 index.html, tendríamos que elegir uno sobre el que basarnos y qué elementos nos gustan de cada uno:

1. https://colorlib.com/polygon/gentelella/index.html
2. https://colorlib.com/polygon/gentelella/index2.html
3. https://colorlib.com/polygon/gentelella/index3.html

Espero vuestra opinión.

**Comment by YamiJoan** [comment]
M'agrada més sa primera vista
